# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:logfile: ./log/sidekiq.log
:concurrency:  5
:queues:
  - [often, 7]
  - [default, 5]
  - [seldom, 3]

